# Generated by Django 5.2.6 on 2025-09-12 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('faculty', 'Faculty'), ('student', 'Student')], max_length=20)),
                ('department', models.CharField(choices=[('COMP', 'COMP'), ('IT', 'IT'), ('AIDS', 'AIDS'), ('AIML', 'AIML'), ('EXTC', 'EXTC'), ('MECH', 'MECH'), ('IOT', 'IOT')], max_length=20)),
                ('year', models.CharField(blank=True, choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
